version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: Microsoft.Data.SqlClient

  - package-ecosystem: github-actions 
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"